FROM docker.io/library/node:22-alpine@sha256:16e22a550f3863206a3f701448c45f7912c6896a62de43add43bb9c86130c3e2
RUN apk upgrade --no-cache
WORKDIR /app
COPY --chmod=0444 his-observability-binding-controller.js /app/controller.js
ENV NODE_EXTRA_CA_CERTS=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt PORT=8080
USER 1000
EXPOSE 8080
CMD ["node", "/app/controller.js"]
