'use strict';

// HIS is a prerequisite contract, not an OpenSphere extension.  Only entries
// in this closed catalog may be mutated by Cluster Manager.  Chart versions
// and payload checksums are also pinned in Dockerfile.
const HIS_CATALOG = Object.freeze([
  {
    id: 'kubernetes-api',
    displayName: 'Kubernetes API',
    description: '지원 Kubernetes API와 제어 평면 응답 상태',
    mode: 'DetectOnly',
    required: true,
    probe: 'kubernetesApi',
    domain: 'Control Plane',
    compatibility: { kubernetes: '>=1.30.0 <1.37.0', policy: 'OpenSphere tested range' },
    remediation: {
      summary: '지원 범위를 벗어난 Kubernetes는 OpenSphere를 변경하기 전에 호스트 제어 평면을 업그레이드하거나 승인된 채널을 선택해야 합니다.',
      steps: ['API server /readyz와 APIService 오류를 확인합니다.', '호스트 Kubernetes 버전을 지원 범위로 맞춥니다.', '다시 검사하여 API discovery와 RBAC self-check를 통과시킵니다.'],
      verification: 'Version range, API discovery, APIService, admission webhook, RBAC self-check',
    },
  },
  {
    id: 'cluster-nodes',
    displayName: 'Node Runtime',
    description: '스케줄 가능한 노드와 kubelet Ready 상태',
    mode: 'DetectOnly',
    required: true,
    probe: 'nodes',
    domain: 'Compute',
    compatibility: { kubernetes: 'control-plane ±1 minor', policy: 'kubelet version-skew policy' },
    remediation: {
      summary: 'NotReady 또는 pressure가 있는 노드는 호스트 운영자가 kubelet·runtime·disk·PID 문제를 해소해야 합니다.',
      steps: ['문제 노드의 Conditions, taint와 kubelet/runtime 버전을 확인합니다.', 'Disk/PID/Memory pressure와 clock/runtime 상태를 복구합니다.', '노드 Ready와 스케줄 가능 상태를 다시 검사합니다.'],
      verification: 'Per-node Ready, pressure, taints, capacity, kubelet/runtime version',
    },
  },
  {
    id: 'cluster-network',
    displayName: 'CNI / Cluster Network',
    description: '호스트가 제공하는 CNI DaemonSet 준비 상태',
    mode: 'DetectOnly',
    required: true,
    probe: 'cni',
    domain: 'Network',
    compatibility: { kubernetes: 'CNI provided by host', policy: 'single healthy primary CNI' },
    remediation: {
      summary: 'CNI는 Cluster Manager가 덮어쓰지 않습니다. 호스트 CNI의 DaemonSet·PodCIDR·NetworkPolicy 지원을 복구해야 합니다.',
      steps: ['CNI DaemonSet의 desired/ready와 이미지를 확인합니다.', '노드 PodCIDR, IP family, NetworkPolicy API를 확인합니다.', '호스트 CNI 절차로 cross-node/egress 통신을 복구한 후 다시 검사합니다.'],
      verification: 'CNI daemon coverage, PodCIDR assignment, IP families, NetworkPolicy API',
    },
  },
  {
    id: 'cluster-dns',
    displayName: 'Cluster DNS',
    description: 'CoreDNS 또는 호환 DNS 서비스 준비 상태',
    mode: 'DetectOnly',
    required: true,
    probe: 'dns',
    domain: 'DNS',
    compatibility: { kubernetes: 'cluster.local discovery', policy: 'internal and external resolution' },
    remediation: {
      summary: 'CoreDNS 배포·Service·Corefile와 upstream forwarder를 점검하고 내부/외부 실제 질의를 모두 복구해야 합니다.',
      steps: ['CoreDNS replica와 kube-dns Service를 확인합니다.', 'Corefile forward/cache 설정과 upstream DNS를 점검합니다.', 'kubernetes.default 및 외부 FQDN 질의를 재검증합니다.'],
      verification: 'Deployment, Service, Corefile, internal/external DNS resolution and latency',
    },
  },
  {
    id: 'ingress-nginx',
    displayName: 'Ingress Controller',
    description: 'IngressClass와 외부 HTTP 진입 경로',
    mode: 'HelmManaged',
    required: true,
    probe: 'ingress',
    release: 'ingress-nginx',
    namespace: 'ingress-nginx',
    chart: '/app/his-charts/ingress-nginx-4.15.1.tgz',
    chartName: 'ingress-nginx',
    chartVersion: '4.15.1',
    appVersion: '1.15.1',
    source: 'https://kubernetes.github.io/ingress-nginx',
    values: [],
    kindValues: ['--values', '/app/his-values/ingress-nginx-kind.yaml'],
    retainedOnDelete: ['Namespace'],
    domain: 'Ingress',
    compatibility: { kubernetes: '>=1.30.0 <1.37.0', policy: 'networking.k8s.io/v1' },
    remediation: {
      summary: 'IngressClass·controller·Service listener·TLS 노출 정책을 함께 복구합니다.',
      steps: ['IngressClass controller 매핑과 controller workload를 확인합니다.', 'Service type, external address와 80/443 listener를 확인합니다.', 'TLS 기본 정책과 실제 endpoint를 검증한 뒤 업그레이드 또는 롤백합니다.'],
      verification: 'IngressClass, controller replicas, service exposure, endpoints, TLS references',
    },
  },
  {
    id: 'cert-manager',
    displayName: 'Certificate Management',
    description: '인증서 CRD와 cert-manager 제어기 준비 상태',
    mode: 'HelmManaged',
    required: true,
    probe: 'certManager',
    release: 'cert-manager',
    namespace: 'cert-manager',
    chart: '/app/his-charts/cert-manager-v1.20.0.tgz',
    chartName: 'cert-manager',
    chartVersion: 'v1.20.0',
    appVersion: 'v1.20.0',
    source: 'oci://quay.io/jetstack/charts/cert-manager',
    values: ['--set', 'crds.enabled=true'],
    kindValues: ['--values', '/app/his-values/cert-manager-kind.yaml'],
    retainedOnDelete: ['Namespace', 'CustomResourceDefinition', '사용자 Certificate/Issuer 데이터'],
    domain: 'Certificate',
    compatibility: { kubernetes: '>=1.30.0 <1.37.0', policy: 'cert-manager CRD v1' },
    remediation: {
      summary: 'cert-manager 제어기뿐 아니라 실제 Issuer와 Certificate 수명주기를 준비해야 합니다.',
      steps: ['CRD, webhook, cainjector readiness를 확인합니다.', 'Issuer/ClusterIssuer Ready와 challenge 실패를 복구합니다.', 'Certificate 만료·갱신 상태와 Secret 소유 정책을 재검증합니다.'],
      verification: 'Controllers, CRDs, issuers, certificates, expiry, orders/challenges',
    },
  },
  {
    id: 'metrics-server',
    displayName: 'Resource Metrics API',
    description: 'kubectl top과 autoscaling이 소비하는 metrics.k8s.io API',
    mode: 'HelmManaged',
    required: true,
    probe: 'metrics',
    release: 'metrics-server',
    namespace: 'kube-system',
    chart: '/app/his-charts/metrics-server-3.13.1.tgz',
    chartName: 'metrics-server',
    chartVersion: '3.13.1',
    appVersion: '0.8.1',
    source: 'https://kubernetes-sigs.github.io/metrics-server',
    values: [],
    kindValues: ['--values', '/app/his-values/metrics-server-kind.yaml'],
    retainedOnDelete: [],
    domain: 'Metrics',
    compatibility: { kubernetes: 'metrics.k8s.io/v1beta1', policy: 'all Ready nodes covered' },
    remediation: {
      summary: 'APIService Available만으로 끝내지 않고 모든 Ready 노드의 최신 metrics가 수집되어야 합니다.',
      steps: ['APIService condition과 metrics-server deployment를 확인합니다.', '노드 metrics coverage와 timestamp를 점검합니다.', 'TLS/kubelet 연결 오류를 복구하고 HPA 소비 경로를 재검증합니다.'],
      verification: 'APIService, deployment, node coverage, freshness, HPA inventory',
    },
  },
  {
    id: 'argocd-runtime',
    displayName: 'Argo CD Runtime',
    description: 'Foundation Platform Delivery의 기본 GitOps write-path runtime',
    mode: 'HelmManaged',
    required: false,
    profile: 'Platform Delivery',
    probe: 'argocd',
    release: 'argocd',
    namespace: 'argocd',
    chart: '/app/his-charts/argo-cd-9.5.15.tgz',
    chartName: 'argo-cd',
    chartVersion: '9.5.15',
    appVersion: 'v3.4.2',
    source: 'https://argoproj.github.io/argo-helm',
    adoptExisting: true,
    values: [
      '--set', 'crds.install=false',
      '--set-string', 'global.image.tag=v3.4.2@sha256:c612d570cb6d6ff29afb72932c1bfe98a1ecc234df50f8ea4873fb7066e760fc',
      '--set-string', 'dex.image.tag=v2.45.1@sha256:b8469881d3cb3a73001506f0d3aaefecb9c45d2311c1e0f405d8ac538316c59d',
      '--set-string', 'redis.image.repository=docker.io/library/redis',
      '--set-string', 'redis.image.tag=8.2.3-alpine@sha256:08ad0b1d280850169a790dba1393ff7a90aef951fc19632cf4d3ce4f78e679ba',
      '--set', 'server.service.type=ClusterIP',
    ],
    retainedOnDelete: [
      'Argo CD CRD',
      'Application/AppProject 선언',
      'repository credential Secret',
      '이미 배포된 workload',
    ],
    domain: 'Platform Delivery',
    compatibility: { kubernetes: '>=1.30.0 <1.37.0', policy: 'Argo CD v3.4.2 · exact image digest · retained CRD' },
    remediation: {
      summary: 'Argo CD controller·API·ApplicationSet runtime을 승인 chart와 exact digest로 설치·복구합니다.',
      steps: ['기존 Kustomize runtime은 최초 승인 시 Helm release로 안전하게 인수합니다.', 'controller·repo-server·server·ApplicationSet readiness를 검증합니다.', 'Application/AppProject와 repository credential은 runtime 제거 시에도 보존합니다.'],
      verification: 'Argo CD CRD discovery, four control-plane workloads, exact-digest images and delivery objects',
    },
  },
  {
    id: 'crossplane-core',
    displayName: 'Crossplane Core',
    description: 'Foundation Platform Delivery가 사용하는 선택적 provisioning adapter의 호스트 runtime',
    mode: 'HelmManaged',
    required: false,
    profile: 'Platform Delivery',
    probe: 'crossplane',
    release: 'crossplane',
    namespace: 'crossplane-system',
    chart: '/app/his-charts/crossplane-2.3.3.tgz',
    chartName: 'crossplane',
    chartVersion: '2.3.3',
    appVersion: '2.3.3',
    source: 'https://charts.crossplane.io/stable',
    values: ['--values', '/app/his-values/crossplane.yaml'],
    kindValues: ['--values', '/app/his-values/crossplane-kind.yaml'],
    adoptExisting: true,
    runtimePolicy: {
      kind: {
        coreImage: 'ghcr.io/opensphere-platform/mirror-crossplane@sha256:cbe8a912ab550fa5b724970f7272428d3a6d13f011d437f3015247be4d14645d',
        providerPackage: 'ghcr.io/opensphere-platform/mirror-crossplane-provider-helm-package@sha256:1e52d72c8f27babe7061a5c8da802cc791b8c492770c89404723f76f8d47a41d',
        providerRuntimeImage: 'ghcr.io/opensphere-platform/mirror-crossplane-provider-helm@sha256:ca8d52dca0adf26c319ae505c2a3f2e835d53ae335cef60ca75d67d7072f3154',
        runtimeConfigName: 'opensphere-provider-helm-linux-amd64',
      },
    },
    preUninstallResources: [
      '/apis/pkg.crossplane.io/v1/providers/crossplane-contrib-provider-helm',
    ],
    preUninstallGuards: [
      {
        label: 'provider-helm Release',
        apiPaths: [
          '/apis/helm.crossplane.io/v1beta1/releases',
          '/apis/helm.m.crossplane.io/v1beta1/releases',
        ],
      },
      {
        label: 'ProviderConfigUsage',
        apiPaths: [
          '/apis/helm.crossplane.io/v1beta1/providerconfigusages',
          '/apis/helm.m.crossplane.io/v1beta1/providerconfigusages',
        ],
      },
      {
        label: 'ProviderConfig',
        allowDefaultInjectedIdentity: true,
        apiPaths: [
          '/apis/helm.crossplane.io/v1beta1/providerconfigs',
          '/apis/helm.m.crossplane.io/v1beta1/providerconfigs',
          '/apis/helm.m.crossplane.io/v1beta1/clusterproviderconfigs',
        ],
      },
    ],
    retainedOnDelete: ['Namespace', 'Crossplane core CustomResourceDefinition'],
    domain: 'Platform Delivery',
    compatibility: { kubernetes: '>=1.30.0 <1.37.0', policy: 'Crossplane v2 package API · provider-helm digest allowlist' },
    remediation: {
      summary: 'Crossplane core·RBAC manager·package API와 승인된 provider-helm을 하나의 HISS revision으로 복구합니다.',
      steps: ['Core CRD와 crossplane/rbac-manager workload readiness를 확인합니다.', 'provider-helm package digest와 ProviderRevision condition을 확인합니다.', 'Foundation의 default ProviderConfig와 managed Release reconcile을 재검증합니다.'],
      verification: 'Core/RBAC manager readiness, package CRD, provider-helm Installed/Healthy, ProviderConfig and Release inventory',
    },
  },
  {
    id: 'kube-prometheus-stack',
    displayName: 'Shared Observability',
    description: 'Prometheus, Grafana, Alertmanager, Loki, Tempo와 OTLP collector를 제공하는 공유 관측 계층',
    mode: 'HelmManaged',
    required: false,
    profile: 'Observability',
    probe: 'kubePrometheusStack',
    release: 'kube-prometheus-stack',
    namespace: 'monitoring',
    chart: '/app/his-charts/kube-prometheus-stack-87.19.1.tgz',
    chartName: 'kube-prometheus-stack',
    chartVersion: '87.19.1',
    appVersion: 'v0.92.1',
    availableChartVersions: ['87.19.1', '86.0.1'],
    chartVariants: [
      { chartVersion: '87.19.1', appVersion: 'v0.92.1', chart: '/app/his-charts/kube-prometheus-stack-87.19.1.tgz' },
      { chartVersion: '86.0.1', appVersion: 'v0.91.0', chart: '/app/his-charts/kube-prometheus-stack-86.0.1.tgz' },
    ],
    source: 'oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack',
    values: ['--values', '/app/his-values/kube-prometheus-stack.yaml'],
    operationalProfile: {
      components: ['Prometheus Operator', 'Prometheus', 'Alertmanager', 'Grafana', 'kube-state-metrics', 'node-exporter', 'Loki', 'Tempo', 'OTLP Collector'],
      storage: ['Grafana 5Gi', 'Alertmanager 2Gi', 'Prometheus 20Gi', 'Loki 10Gi', 'Tempo 10Gi'],
      retention: ['Alertmanager 120h', 'Prometheus 7d', 'Logs/Traces 168h'],
      exposure: 'ClusterIP only (Ingress disabled)',
    },
    retainedOnDelete: ['Namespace', 'CustomResourceDefinition', 'PersistentVolumeClaim', 'Prometheus/Alertmanager/Loki/Tempo 관측 데이터'],
    domain: 'Observability',
    compatibility: { kubernetes: '>=1.30.0 <1.37.0', policy: 'Prometheus Operator CRD v1' },
    remediation: {
      summary: '관측 구성요소·영구 저장소·내부 접근 정책·알림 경로를 하나의 관리 revision으로 복구합니다.',
      steps: ['구성요소, CRD, PVC와 Service 상태를 확인합니다.', '저장소·보존·Grafana 노출 변경 계획을 검토합니다.', 'Helm apply 후 metric·alert·OTLP log/trace 저장·조회 검증을 수행하고 실패 시 이전 revision으로 롤백합니다.'],
      verification: 'Six components, CRDs, PVCs, ClusterIP exposure, scrape and alert readiness',
    },
  },
  {
    id: 'storage',
    displayName: 'Storage Provisioning',
    description: '기본 StorageClass와 동적 provisioner',
    mode: 'DetectOnly',
    required: true,
    probe: 'storage',
    domain: 'Storage',
    compatibility: { kubernetes: 'storage.k8s.io/v1', policy: 'exactly one CSI-backed default dynamic provisioner required' },
    remediation: {
      summary: 'StorageClass 선택은 데이터 수명주기 결정입니다. 등록된 CSI·binding·expansion·reclaim·topology를 함께 검토합니다.',
      steps: ['StorageClass matrix와 기본값 중복을 확인합니다.', '기본 provisioner가 실제 CSIDriver와 일치하는지 검증합니다.', 'reclaim Delete와 비확장 class의 데이터 위험을 승인하고 PVC bind canary를 수행합니다.'],
      verification: 'StorageClass/CSIDriver mapping, default uniqueness, PVC inventory, expansion/reclaim/topology risk',
    },
  },
  {
    id: 'csi-snapshot',
    displayName: 'CSI / Volume Snapshot',
    description: 'CSI Driver와 VolumeSnapshot capability (profile 선택 시 필수)',
    mode: 'DetectOnly',
    required: false,
    profile: 'Data Protection',
    probe: 'snapshot',
    domain: 'Data Protection',
    compatibility: { kubernetes: 'snapshot.storage.k8s.io/v1', policy: 'CSI driver and snapshot controller required' },
    remediation: {
      summary: 'CSI Driver만으로 snapshot capability가 완성되지 않습니다. controller·CRD·class와 restore 경로가 모두 필요합니다.',
      steps: ['CSIDriver와 controller deployment를 확인합니다.', 'VolumeSnapshot CRD와 VolumeSnapshotClass driver 매핑을 확인합니다.', 'snapshot→restore canary와 topology/access/encryption 정책을 검증합니다.'],
      verification: 'Drivers, controllers, snapshot CRDs/classes, snapshot inventory, restore canary',
    },
  },
]);

function catalogItem(id) {
  return HIS_CATALOG.find((item) => item.id === id);
}

module.exports = { HIS_CATALOG, catalogItem };
