FROM xpkg.crossplane.io/crossplane-contrib/provider-helm@sha256:ca5056cb56c9f95afda84fcb0b9e0d6de2cb86fa8e0adbc09e6ccdbb4b9b4370

LABEL org.opencontainers.image.source="https://github.com/crossplane-contrib/provider-helm" \
      org.opencontainers.image.revision="df02f201fec49fdabd095421bc3b0a67b1b296b6" \
      org.opencontainers.image.version="202607010129" \
      io.opensphere.source-revision="df02f201fec49fdabd095421bc3b0a67b1b296b6" \
      io.opensphere.release-tag="202607010129" \
      io.opensphere.channel="edge" \
      opensphere.io/build-authority="localhost" \
      opensphere.io/release-class="pre-ga" \
      opensphere.io/ga-eligible="false" \
      opensphere.io/upstream-version="v1.3.0" \
      opensphere.io/upstream-image-digest="sha256:ca5056cb56c9f95afda84fcb0b9e0d6de2cb86fa8e0adbc09e6ccdbb4b9b4370"
