FROM xpkg.crossplane.io/crossplane/crossplane@sha256:24f97138c7d04eee229de947652b4425207bffd40d96e50815a03ed742bac4c4

LABEL org.opencontainers.image.source="https://github.com/crossplane/crossplane" \
      org.opencontainers.image.revision="09ffaea39ccaea0f80817e35b5bbd3632b4e7e0d" \
      org.opencontainers.image.version="202606222233" \
      io.opensphere.source-revision="09ffaea39ccaea0f80817e35b5bbd3632b4e7e0d" \
      io.opensphere.release-tag="202606222233" \
      io.opensphere.channel="edge" \
      opensphere.io/build-authority="localhost" \
      opensphere.io/release-class="pre-ga" \
      opensphere.io/ga-eligible="false" \
      opensphere.io/upstream-version="v2.3.3" \
      opensphere.io/upstream-image-digest="sha256:24f97138c7d04eee229de947652b4425207bffd40d96e50815a03ed742bac4c4"
