import {
  angleIcon,
  applicationsIcon,
  blockIcon,
  ClarityIcons,
  clusterIcon,
  computerIcon,
  cpuIcon,
  dashboardIcon,
  devicesIcon,
  downloadIcon,
  ellipsisVerticalIcon,
  eyeIcon,
  fileGroupIcon,
  gridViewIcon,
  layersIcon,
  memoryIcon,
  networkGlobeIcon,
  pauseIcon,
  pencilIcon,
  playIcon,
  popOutIcon,
  rackServerIcon,
  refreshIcon,
  resizeIcon,
  searchIcon,
  shieldIcon,
  stopIcon,
  storageIcon,
  successStandardIcon,
  terminalIcon,
  timesIcon,
  trashIcon,
  twoWayArrowsIcon,
  vmIcon,
  warningStandardIcon,
} from '@clr/angular';

/** nav-icons.ts의 shape와 함께 변경해야 하는 런타임 등록 목록. */
export const REGISTERED_NAV_ICON_NAMES = [
  'applications',
  'cluster',
  'dashboard',
  'network-globe',
  'rack-server',
  'shield',
  'storage',
  'two-way-arrows',
  'vm',
] as const;

/** 템플릿과 동적 UI에서 직접 사용하는 모든 아이콘. 미등록 아이콘은 `unknown`(…)으로 보인다. */
export const REGISTERED_UI_ICON_NAMES = [
  'angle',
  'block',
  'computer',
  'cpu',
  'devices',
  'download',
  'ellipsis-vertical',
  'eye',
  'file-group',
  'grid-view',
  'layers',
  'memory',
  'pause',
  'pencil',
  'play',
  'pop-out',
  'refresh',
  'resize',
  'search',
  'stop',
  'success-standard',
  'terminal',
  'times',
  'trash',
  'warning-standard',
] as const;

export function registerClusterManagerIcons(): void {
  ClarityIcons.addIcons(
    angleIcon,
    applicationsIcon,
    blockIcon,
    clusterIcon,
    computerIcon,
    cpuIcon,
    dashboardIcon,
    devicesIcon,
    downloadIcon,
    ellipsisVerticalIcon,
    eyeIcon,
    fileGroupIcon,
    gridViewIcon,
    layersIcon,
    memoryIcon,
    networkGlobeIcon,
    pauseIcon,
    pencilIcon,
    playIcon,
    popOutIcon,
    rackServerIcon,
    refreshIcon,
    resizeIcon,
    searchIcon,
    shieldIcon,
    stopIcon,
    storageIcon,
    successStandardIcon,
    terminalIcon,
    timesIcon,
    trashIcon,
    twoWayArrowsIcon,
    vmIcon,
    warningStandardIcon,
  );
}
